### ISSUE TITLE
Snippets not working correctly

### ISSUE THREAD

**Issue by douglas86** [neoclide/coc-snippets#188] opened 2020-12-06 09:26 UTC
When I insert my own custom snippet, and try using it in my program it prints out funny characters, and duplicates the snippet. Any suggestions on how to fix:

this is my custom snippet:
snippet forEach "forEach loop"           
 ${1:arr}.forEach(${2:item} => {          
      ${0}                                                                                                                          
 })
 endsnippet

This is what is printed out when I use the snippet:
v45G3|o45G1|o.forEach(item => {
       
 })Each(item => {
     
})

Any suggestions on how to fix

**Comment by chemzqm** [comment] 2020-12-06 10:43
Try minimal vimrc

**Comment by douglas86** [comment] 2020-12-06 12:41
I was hoping to sort it out in neovim. There must be a small section that I am missing.

**Comment by jerssonMA** [comment] 2020-12-06 18:15
Something similar happens to me, yesterday I updated the library and duplicating the generated code.

Snippet
`
snippet imp "import from ''" b
import { $2 } from '$1';
endsnippet
`

Result
`
import {  } from '';ort {  } from '';
`

**Comment by chemzqm** [comment] 2020-12-07 01:59
@jerssonMA it was anther issue that has been fixed

**Comment by jerssonMA** [comment] 2020-12-07 15:04
@chemzqm I keep presenting the error currently

**Comment by chemzqm** [comment] 2020-12-07 15:19
Please provide minimal vimrc.

**Comment by jerssonMA** [comment] 2020-12-07 15:21
My vim config repo https://github.com/jerssonM/personal_shell_config.
the coc setting is in [plugins-config.vim](https://github.com/jerssonM/personal_shell_config/blob/main/plugins-config.vim)

**Comment by chemzqm** [comment] 2020-12-07 15:57
Minimal vimrc, use `vim -u mini.vim` for custom vimrc.

**Comment by jerssonMA** [comment] 2020-12-07 16:06
Excuse me but what should happen when executing this command, I am not sure. I am running it on my vimrc.

**Comment by jerssonMA** [comment] 2020-12-07 20:03
Apparently the problem is with this function any idea that is wrong? I took it from the coc documentation.
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

```

**Comment by douglas86** [comment] 2020-12-09 08:36
@jerssonMA what did you place in your vimrc to fix that issue.

**Comment by jerssonMA** [comment] 2020-12-09 14:37
@douglas86 The only solution at the moment is not to use the tab to select the snippets, I am using the movement arrows but I would like to continue using the tab. @chemzqm do you have any idea why this error occurs?

**Comment by chemzqm** [comment] 2020-12-09 14:42
No, can't reproduce

**Comment by jerssonMA** [comment] 2020-12-09 21:11
@chemzqm If you add this function to your vimrc and use the tab to select a snippet and then expand it generates this error.

```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

```

**Comment by chemzqm** [comment] 2020-12-10 04:18
No, I can't reproduce, how did trigger expand?

**Comment by jerssonMA** [comment] 2020-12-10 14:51
Select the snippet with the tab and then press ctrl - l to expand it.
`imap <C-l> <Plug>(coc-snippets-expand)`
I have managed to detect that this error only happens when you have enough code in a file.

This is an example with a random code

![CleanShot 2020-12-10 at 09 50 38](https://user-images.githubusercontent.com/65183481/101787559-3a8da480-3acd-11eb-86df-268d3ad93da7.gif)

**Comment by jerssonMA** [comment] 2020-12-18 16:25
@chemzqm when updating the latest version of coc, the problem stopped presenting.

**Comment by chemzqm** [comment] 2021-08-23 07:42
Should be fixed on coc.nvim.

**Closed by chemzqm** 2021-08-23 07:42 UTC
Labels: Can't reproduce
