### ISSUE TITLE
custom vscode snippets not working

### ISSUE THREAD

**Issue by GabrielDuarteM** [neoclide/coc-snippets#127] opened 2020-04-18 17:41 UTC
On the coc-settings.json, I have `"snippets.textmateSnippetsRoots": ["~/.config/nvim/vscode-global-snippets"]`. After, I created a file named `.config/nvim/vscode-global-snippets/global-snippets.code-snippets` containing 
```json
{
  "Lorem ipsum (50 words)": {
    "body": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
    "prefix": "lorem",
    "description": "Lorem ipsum (50 words)"
  }
}
```

After this, if I go to any file and type `lorem`, and hit the autocomplete, I'd expect the snippet to show up, but it doesn't. It also doesn't show up when I call `:CocList snippets` (the only ones that shows up are the snippets declare by extensions). It doesn't give out any error.

For now, I created a custom vscode extension to store my custom snippets, and if I drop the same snippet there, it works.

If I run `:CocCommand workspace.showOutput snippets`, it opens a new blank split, even though I'd expect at least the extension snippets to show up there, as they are working normally.

Do I have to configure something differently?

My full coc-settings.json: 

```json
  "coc.preferences.formatOnSaveFiletypes": ["javascript", "typescript", "typescriptreact", "json", "javascriptreact", "python"],
  "suggest.detailField": "preview",
  "suggest.completionItemKindLabels": {
        "keyword": "",
        "variable": "",
        "value": "",
        "operator": "Ψ",
        "function": "⨕",
        "reference": "渚",
        "constant": "",
        "method": "",
        "struct": "פּ",
        "class": "",
        "interface": "",
        "text": "♣",
        "enum": "",
        "enumMember": "",
        "module": "",
        "color": "",
        "property": "",
        "field": "",
        "unit": "",
        "event": "鬒",
        "file": "",
        "folder": "",
        "snippet": "",
        "typeParameter": "",
        "default": ""
  },
  "coc.preferences.snippetStatusText": "Ⓢ ",
  "eslint.filetypes": ["javascript", "typescript", "typescriptreact", "javascriptreact"],
  "prettier.onlyUseLocalVersion": true,
  "git.changedSign.text": "",
  "git.changedSign.hlGroup": "GitGutterChange",
  "git.addedSign.text": "",
  "git.addedSign.hlGroup": "GitGutterAdd",
  "git.removedSign.text": "",
  "git.removedSign.hlGroup": "GitGutterDelete",
  "git.topRemovedSign.text": "",
  "git.topRemovedSign.hlGroup": "GitGutterDelete",
  "git.changeRemovedSign.text": "",
  "git.changeRemovedSign.hlGroup": "GitGutterChangeDelete",
  "diagnostic.virtualText": true,
  "snippets.textmateSnippetsRoots": ["~/.config/nvim/vscode-global-snippets"],
  "snippets.ultisnips.enable": false
}
```

**Comment by Nohac** [comment] 2020-07-30 09:49
Any updates on this?

Also, to add to this issue. Vscode can have project scoped snippets that it reads from `.vscode/<filename>.code-snippets`. This would be nice to have in order to share snippets with others that use vscode.
For reference: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_project-snippet-scope

**Comment by MrVizious** [comment] 2020-08-08 02:49
I'd also like to know if there are any advancements, I am having trouble here to get this working

**Comment by REslim30** [comment] 2020-09-08 23:22
Have you guys tried using the absolute path? e.g. instead of:
"snippets.textmateSnippetsRoots": ["~/.config/nvim/vscode-global-snippets"]

"snippets.textmateSnippetsRoots": ["/home/user/.config/nvim/vscode-global-snippets"],

So on the github it says:
"snippets.textmateSnippetsRoots: **absolute** directories that contains textmate/VSCode snippets to load."
So I'm assuming it doesn't support tilde expansion.

**Comment by ta-tikoma** [comment] 2020-09-15 10:15
I set full path:
```
    "snippets.ultisnips.enable": false,
    "snippets.textmateSnippetsRoots": [
        "c:\\Users\\ta\\AppData\\Local\\nvim\\snippets"
    ],
```
in coc-settings.json
but `CocCommand workspace.showOutput snippets` show nothing (

**Comment by pixelstorm** [comment] 2020-11-21 02:38
ensure each snippet in your custom snippets file has the closing 'endsnippet' statement

**Comment by BStephenBB** [comment] 2020-12-30 07:16
> ensure each snippet in your custom snippets file has the closing 'endsnippet' statement

The `endsnippet` statement is used for ultisnips, not for vs code snippets.

---

I am running into the same problem as other above and have tried using both an absolute path and tilde expansion. I would love to be able to point coc-snippets at my vscode snippets and then all my snippets for vscode and vim can be shared.

The docs say you can:
> Load VSCode snippets from custom directories.

But it doesn't seem possible. Should the docs be changed, or is this a bug? If I can find the time I'd be happy to try and debug and make a PR. Has anyone else had any luck getting this to work or figured out the cause of the bug?

**Comment by chemzqm** [comment] 2020-12-30 07:26
It could only load VSCode snippets inside folder of `snippets.textmateSnippetsRoots` with `[languageId].json` and `[languageId].code-snippets`

**Comment by BStephenBB** [comment] 2020-12-30 08:53
> It could only load VSCode snippets inside folder of `snippets.textmateSnippetsRoots` with `[languageId].json` and `[languageId].code-snippets`

Oh wow, that works; thanks! And thanks for all the work you do on coc! Maybe we should add ^ this to the FAQ? I'd be happy to make a PR if you think that'd be helpful.

**Comment by chemzqm** [comment] 2020-12-30 09:23
Sure, PR welcome.

**Closed** 2022-02-27 20:00 UTC
Labels: enhancement, help wanted
