### ISSUE TITLE
completion very slow on ubuntu-server but not on arch

### ISSUE THREAD

**Issue by divramod** [neoclide/coc-snippets#184] opened 2020-11-10 10:59 UTC
Hey, 

i am running coc-snippet on arch and on ubuntu-server.
On arch the completions run more or less instantly but on ubuntu-server it takes on average 3 seconds to complete, independent from the filetype i use it in.
I tried it with a minimal neovim configuration but the problem stays the same.
Can someone give me an idea on how to start to debug that problem?

I really like coc-snippets. Thx for the awesome plugin!

CocInfo output on the ubuntu-server:
```

## versions

vim version: NVIM v0.4.3
node version: v12.10.0
coc.nvim version: 0.0.79-be822b546f
coc.nvim directory: /root/dev/dotfiles/nvim/plug/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-10T11:44:54.793 INFO (pid:707205) [services] - registered service "eslint"
2020-11-10T11:44:54.898 INFO (pid:707205) [services] - registered service "highlight"
2020-11-10T11:44:55.615 INFO (pid:707205) [services] - registered service "reason"
2020-11-10T11:44:55.666 INFO (pid:707205) [language-client-index] - highlight started with 707719
2020-11-10T11:44:55.735 INFO (pid:707205) [services] - registered service "sh"
2020-11-10T11:44:55.736 INFO (pid:707205) [services] - bash-language-server state change: stopped => starting
2020-11-10T11:44:55.859 INFO (pid:707205) [services] - registered service "tsserver"
2020-11-10T11:44:55.966 INFO (pid:707205) [language-client-index] - Language server "sh" started with 707735
2020-11-10T11:44:56.001 INFO (pid:707205) [plugin] - coc.nvim 0.0.79-be822b546f initialized with node: v12.10.0 after 2329ms
2020-11-10T11:44:56.056 INFO (pid:707205) [services] - service tsserver started
2020-11-10T11:44:56.588 INFO (pid:707205) [completion-complete] - Results from: around,buffer
2020-11-10T11:45:00.776 INFO (pid:707205) [completion-complete] - Results from: snippets,syntax,around,buffer
2020-11-10T11:45:03.000 INFO (pid:707205) [services] - bash-language-server state change: starting => running
2020-11-10T11:45:03.003 INFO (pid:707205) [services] - service sh started
2020-11-10T11:45:41.659 INFO (pid:707205) [completion-complete] - Results from: tsserver-typescript
2020-11-10T11:45:43.536 INFO (pid:707205) [willSaveHandler] - Will save cost: 62
2020-11-10T11:46:10.765 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,around,buffer,tsserver-typescript
2020-11-10T11:46:12.101 INFO (pid:707205) [completion-complete] - Results from: tsserver-typescript
2020-11-10T11:46:14.496 INFO (pid:707205) [completion-complete] - Results from: around,buffer,syntax,snippets,tsserver-typescript
2020-11-10T11:46:16.250 INFO (pid:707205) [willSaveHandler] - Will save cost: 64
2020-11-10T11:46:39.246 INFO (pid:707205) [willSaveHandler] - Will save cost: 66
2020-11-10T11:48:11.521 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,around,buffer,tsserver-typescript
2020-11-10T11:48:14.050 INFO (pid:707205) [completion-complete] - Results from: tsserver-typescript
2020-11-10T11:48:15.487 INFO (pid:707205) [completion-complete] - Results from: snippets,syntax,around,buffer,tsserver-typescript
2020-11-10T11:48:17.434 INFO (pid:707205) [willSaveHandler] - Will save cost: 62
2020-11-10T11:48:57.574 INFO (pid:707205) [willSaveHandler] - Will save cost: 63
2020-11-10T11:49:16.481 INFO (pid:707205) [willSaveHandler] - Will save cost: 62
2020-11-10T11:49:16.590 INFO (pid:707205) [willSaveHandler] - Will save cost: 62
2020-11-10T11:49:18.932 INFO (pid:707205) [willSaveHandler] - Will save cost: 65
2020-11-10T11:50:11.742 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,around,buffer,tsserver-typescript
2020-11-10T11:50:36.792 INFO (pid:707205) [completion-complete] - Results from: around,buffer,syntax,snippets,yank,tsserver-typescript
2020-11-10T11:50:42.813 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,buffer
2020-11-10T11:50:44.299 INFO (pid:707205) [willSaveHandler] - Will save cost: 65
2020-11-10T11:51:41.579 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,around,buffer,tsserver-typescript
2020-11-10T11:55:05.115 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,around,buffer,tsserver-typescript
2020-11-10T11:55:08.530 ERROR (pid:707205) [attach] - Request cost more than 3s doKeymap [ 'snippets-expand-jump' ]
2020-11-10T11:55:12.275 INFO (pid:707205) [completion-complete] - Results from: snippets,yank,syntax,around,buffer,tsserver-typescript
2020-11-10T11:55:15.953 ERROR (pid:707205) [attach] - Request cost more than 3s doKeymap [ 'snippets-expand-jump' ]
```

**Comment by chemzqm** [comment] 2020-11-10 11:12
No idea, could be the disk of your computed is too slow.

**Comment by divramod** [comment] 2020-11-11 07:22
no, its a fast one. do you have an idea how i can debug that? ie see, where coc will hang?

**Comment by chemzqm** [comment] 2020-11-11 07:41
Try check this function https://github.com/neoclide/coc.nvim/blob/master/src/snippets/manager.ts#L57 https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim#using-logger-module-recommended use `Date.now()` to get current timestamp.

**Comment by ypomortsev** [comment] 2020-11-20 06:18
The problem is that coc's [SnippetVariableResolver](https://github.com/neoclide/coc.nvim/blob/master/src/snippets/variableResolve.ts#L20) invokes `xsel`, through clipboardy, for every snippet expansion even if the snippet does not use the CLIPBOARD variable.

This is pretty slow on Debian, where `xsel` takes up to 200ms for me. On Manjaro (Arch), `xsel` returns in 2ms.

**Comment by divramod** [comment] 2020-11-29 07:19
ah ok, do you have any idea on how to solve that problem on ubuntu?

**Comment by chemzqm** [comment] 2020-11-29 12:47
Fixed on latest release branch of coc.nvim.

**Closed by chemzqm** 2020-11-29 12:47 UTC
Labels: Can't reproduce
