### ISSUE TITLE
UltiSnips transformation on the same line causes Vim to sometimes leave snippet-mode

### ISSUE THREAD

**Issue by Melkster** [neoclide/coc-snippets#157] opened 2020-07-20 21:18 UTC
**Expected behavior:**
LaTeX snippet with transformation should replace all spaces with dashes.

**Actual behavior:**
Vim seems to jump out of snippet-mode randomly, particularly when typing quickly. However, splitting the snippet so that the transformation is on the next line however seems to solve the issue.

**Steps to reproduce**

1. Use the following minimal `init.vim`:

```vim
call plug#begin('~/.vim/bundle')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

let g:tex_flavor = 'latex'
let g:coc_global_extensions = [
\ 'coc-snippets'
\]
```

2. Use the following file at `~/.config/coc/ultisnips/tex.snippets`:

```snippets
snippet sec "\section" b
\\section{${1:section name}} \\label{sec:${2:${1/\s/-/g}}}
${0}
endsnippet
```

3. Do `nvim foo.tex`.
4. Type `sec` and press enter to select the snippet `sec`.
5. Type something like `foo bar foo bar` quickly.
6. Vim should eventually jump out of snippet-mode and the text you're writing is therefore not mirrored nor transformed, giving a result similar to the following which I got:

```tex
\section{foo bar}foo bar \label{sec:foo-bar}
```

- **Operating System**: Antergos Linux x86_64
- **Vim Version**: NVIM v0.5.0-593-g1ca67a73c

**Comment by lambtho12** [comment] 2020-08-15 21:46
I am new to coc-snippets, so maybe I am wrong, but isn't this due to the fact that "Reformat after change of placeholder feature can't be supported for now"?

I don't know. I have been using UltiSnips for quite some time and I am quite accustomed to these snippets. Almost all snippets with regexp seems broken using coc-snippets (table, fig, sub, ...) and I am not sure if there is a fix for this or not.

**Comment by chemzqm** [comment] 2020-09-10 16:38
Looks like `${1/\s/-/g}` in incompatible with snipmate format of coc.nvim.

**Comment by chemzqm** [comment] 2020-11-16 13:05
@lambtho12 it can't reformat placeholder with python code or regexp that can't convert to javascript.

Can't reproduce now, might be fixed.

**Closed by chemzqm** 2020-11-16 13:05 UTC
Labels: Can't reproduce
