### ISSUE TITLE
UnicodeDecodeError on windows

### ISSUE THREAD

**Issue by fcying** [neoclide/coc-snippets#144] opened 2020-06-07 08:09 UTC
it work fine on linux
on windows. when I start nvim , it jump a error.

```
python3 --version
Python 3.8.3
```

```
[coc.nvim] Error on execute python script: request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
error caught in request handler 'python_execute_file ['C:\\Users\\nas\\AppData\\Local\\Temp\\coc.nvim-13120\\coc-ultisnips-4jzXFyz6ZB.py', 1, 1]':
Traceback (most recent call last):
  File "D:\tool\scoop\apps\python\current\lib\site-packages\pynvim\plugin\script_host.py", line 106, in python_execute_file
    script = compile(f.read(), file_path, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 17988: illegal multibyte sequence
```

[coc-ultisnips-4jzXFyz6ZB.py.txt](https://github.com/neoclide/coc-snippets/files/4741556/coc-ultisnips-4jzXFyz6ZB.py.txt)

**Comment by chemzqm** [comment] 2020-06-09 07:26
Duplicate of #124

**Closed by chemzqm** 2020-06-09 07:26 UTC
