### ISSUE TITLE
Snippet expansion causes IndexError when expanding with C-j

### ISSUE THREAD

**Issue by sebiwi** [neoclide/coc-snippets#113] opened 2020-03-14 19:08 UTC
Hello,

I added the `imap <C-j> <Plug>(coc-snippets-expand-jump)` option on my vimrc so that coc-snippets works as UltiSnips. I  installed both coc-go and vim-go. When I try to expand the `func` snippet, I get the following error (which gets inserted in the text file under edition):

```
func :qa(params)Traceback (most recent call last):
File "<string>", line 3, in <module>
File "/var/folders/rv/wpk98b2x2xb9rddt8qsbtgld3gkt95/T/coc.nvim-3813/coc-ultisnips-75fc5519f5376d25ad59f5f2188d81ec.py", line 282, in opening_par
if return_values(t[pos]) > 1 and not t[pos].startswith("("):
IndexError: tuple index out of rangeTraceback (most recent call last):
File "<string>", line 3, in <module>
File "/var/folders/rv/wpk98b2x2xb9rddt8qsbtgld3gkt95/T/coc.nvim-3813/coc-ultisnips-75fc5519f5376d25ad59f5f2188d81ec.py", line 288, in closing_par
if return_values(t[pos]) > 1:
IndexError: tuple index out of range {
	
}
```
This doesn't happen if I expand the snippet using `<CR>`.

This is my coc configuration:

```
""""""""""""""""""""""""""""
"  CoC configuration
""""""""""""""""""""""""""""
" let g:coc_global_extensions = [ 'coc-emoji', 'coc-eslint', 'coc-prettier', 'coc-tsserver', 'coc-tslint', 'coc-tslint-plugin', 'coc-css', 'coc-json', 'coc-pyls', 'coc-yaml' ]
let g:coc_global_extensions = [ 'coc-go', 'coc-ultisnips', 'coc-json', 'coc-yaml' ]

" Better display for messages
" set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
" Use <C-j> for both expand and jump (make expand higher priority.)
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
imap <C-j> <Plug>(coc-snippets-expand-jump)
" Or use `complete_info` if your vim support it, like:
" inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"

" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

" Remap for rename current word
nmap <leader>rn <Plug>(coc-rename)

" Remap for format selected region
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap for do codeAction of current line
" nmap <leader>ac  <Plug>(coc-codeaction)
" Fix autofix problem of current line
" nmap <leader>qf  <Plug>(coc-fix-current)

" Create mappings for function text object, requires document symbols feature of languageserver.
xmap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap if <Plug>(coc-funcobj-i)
omap af <Plug>(coc-funcobj-a)

" Use <C-d> for select selections ranges, needs server support, like: coc-tsserver, coc-python
" nmap <silent> <C-d> <Plug>(coc-range-select)
" xmap <silent> <C-d> <Plug>(coc-range-select)

" Use `:Format` to format current buffer
" command! -nargs=0 Format :call CocAction('format')

" Use `:Fold` to fold current buffer
" command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" use `:OR` for organize import of current buffer
" command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add status line support, for integration with other plugin, checkout `:h coc-status`
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Using CocList
" Show all diagnostics
nnoremap <silent> <space>ca  :<C-u>CocList diagnostics<cr>
" Manage extensions
nnoremap <silent> <space>ce  :<C-u>CocList extensions<cr>
" Show commands
nnoremap <silent> <space>cc  :<C-u>CocList commands<cr>
" Find symbol of current cdocument
nnoremap <silent> <space>co  :<C-u>CocList outline<cr>
" Search workspace symbolcs
nnoremap <silent> <space>cs  :<C-u>CocList -I symbols<cr>
" Do default action for ncext item.
nnoremap <silent> <space>cj  :<C-u>CocNext<CR>
" Do default action for pcrevious item.
nnoremap <silent> <space>ck  :<C-u>CocPrev<CR>
" Resume latest coc list
nnoremap <silent> <space>cp  :<C-u>CocListResume<CR>
```

I'm using:
MacOS Mojave 10.14.6
vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2020 22:40:59)
node version: v12.16.1
coc.nvim version: 0.0.76-2c7c3417b3
term: iTerm.app
platform: darwin

Thanks!

Edit: add coc configuration.

**Comment by chemzqm** [comment] 2020-04-09 12:31
Unabled to reproduce.

**Comment by chemzqm** [comment] 2020-04-09 12:33
Duplicate of #93 93

**Closed by chemzqm** 2020-04-09 12:33 UTC
Labels: Can't reproduce
