### ISSUE TITLE
original uppercase pattern of UltiSnips doesn't run in coc-snippets

### ISSUE THREAD

**Issue by sfpmld** [neoclide/coc-snippets#62] opened 2019-09-16 11:16 UTC
Hi, I've migrated to coc.snippets to take care of my snippets, but I have this pb with uppercase pattern.

I'm trying to have this pattern wich was working well with simple Ultisnips plugin but don't work with coc-snippets 

```
snippet mongs "Mongoose Schema Boilerplate" b
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ${1:schema_name}Schema = new Schema({
	${2:field_name}: {
		type: ${3:String|Number|Date|Object|Buffer|Boolean|Schema.Types.ObjectID},
		required: ${4:true|false},
		${5://...}
	},
	${6://...}
}${7:, \{ timestamps: true \}});


module.exports = mongoose.model('${1/\w+\s*/\u$0/g}',$1Schema);
endsnippet
```

if $1 = **recipe** : we would have mongoose.model('**Recipe**',recipeSchema);

Ultisnips plugin was expanding this pattern ${1/\w+\s*/\u$0/g} with the first letter in uppercase.
I really need this behaviour in coc-snippets. 
Is it a bug?

My config: 

## versions

vim version: NVIM v0.4.0-1155-gc62690ccc
node version: v10.16.0
coc.nvim version: 0.0.74-c97d41aa1e
term: screen-256color
platform: linux

##

thanks in advance
Have a good day!

**Comment by chemzqm** [comment] 2019-09-16 12:09
We don't have `\u$0` with javascript, duplicate of \u$0

**Closed by chemzqm** 2019-09-16 12:09 UTC

**Comment by sfpmld** [comment] 2019-09-16 14:50
Ok thank you for your fast response!

**Comment by sfpmld** [comment] 2019-09-16 16:00
I was thinking about possibility to keep using UltiSnips aside coc.nvim. Is this possible? Cause I'm using only coc for my autocompleting, and I like it. But I would like to be able to use original Ultisnips plugin to access some specifics features.

**Comment by chemzqm** [comment] 2019-09-16 16:28
You can

**Comment by sfpmld** [comment] 2019-09-17 09:21
What is your indications to do so. Cause when I just uninstall coc-snippets, specify directories of snippets for UltiSnips plugin. Unfortunatly, coc.nvim don't propose Ultisnips snipppets list. How to do so?

**Comment by chemzqm** [comment] 2019-09-17 09:34
There is coc-ultisnips for completion of snippet trigger https://github.com/neoclide/coc-sources, but it's less featured than coc-snippets.

**Comment by sfpmld** [comment] 2019-09-18 06:32
Thank you, I' ll give a try today.
