### ISSUE TITLE
Auto Import Issue

### ISSUE THREAD

**Issue by ovidius72** [neoclide/coc-snippets#72] opened 2019-11-14 23:27 UTC
In a typescript file, with auto import enalbled, auto completing a word that perform an auto import the snippets stops . You cannot step in into other tab stops and placehoders are not updated.
Is this the default behaviour or maybe there is something wrong with my configuration ? 
Thanks.

**Comment by chemzqm** [comment] 2020-01-04 07:09
Can't reproduce.

**Comment by ovidius72** [comment] 2020-01-04 08:34
This is a quick example.
![vim-snippets2](https://user-images.githubusercontent.com/3592928/71762825-d9307f00-2ed4-11ea-95af-349cf4e18913.gif)
The first time I select the item(membershipRoles) from the list just hitting Ctrl-J but it's not auto imported and it keeps working fine. 
The second time I press Return on the item so that the membersipRoles variable is auto imported but the snippets stops working. Clicking Ctrl-J or Ctrl-K to go to the next placeholder doesn´t work.

**Comment by chemzqm** [comment] 2020-03-17 04:17
Fixed on coc.nvim.

**Closed by chemzqm** 2020-03-17 04:17 UTC
Labels: Can't reproduce
