### ISSUE TITLE
request dokeymap timeout

### ISSUE THREAD

**Issue by newbeenew** [neoclide/coc-snippets#176] opened 2020-09-15 03:29 UTC
`FUNCTION  <SNR>99_request()
    Defined: ~/.vim/plugged/coc.nvim/autoload/coc/client.vim:134
Called 1 `time`
Total time:  60.064897
 Self time:  60.060360

count  total (s)   self (s)
    1   0.000037   0.000024   let channel = coc#client#get_channel(self)
    1              0.000014   if empty(channel) | return '' | endif
    1              0.000004   try
    1              0.000004     if s:is_vim
    1  60.064690  60.060166       let res = ch_evalexpr(channel, [a:method, a:args], {'timeout': 60 * 1000})
    1              0.000008       if type(res) == 1 && res ==# ''
    1              0.000010         throw 'request '.a:method. ' '.string(a:args).' timeout after 60s'
                                  endif
                                  let [l:errmsg, res] =  res
                                  if !empty(l:errmsg)
                                    throw l:errmsg
                                  else
                                    return res
                                  endif
                                else
                                  return call('rpcrequest', [channel, a:method] + a:args)
                                endif
    1              0.000030   catch /.*/
    1              0.000004     if v:exception =~# 'E475'
                                  if get(g:, 'coc_vim_leaving', 0) | return | endif
                                  echohl Error | echom '['.self.name.'] server connection lost' | echohl None
                                  let name = self.name
                                  call s:on_exit(name, 0)
                                  execute 'silent do User ConnectionLost'.toupper(name[0]).name[1:]
    1              0.000002     elseif v:exception =~# 'E12'
                                  " neovim's bug, ignore it
    1              0.000000     else
    1              0.000052       echohl Error | echo 'Error on request ('.a:method.'): '.v:exception | echohl None
    1              0.000000     endif
    1              0.000016   endtry

FUNCTION  coc#util#unplace_signs()
    Defined: ~/.vim/plugged/coc.nvim/autoload/coc/util.vim:721
Called 1 time
Total time:   0.000019
 Self time:   0.000019

> ```

**Comment by gongxiao** [comment] 2020-09-30 01:29
this problem may only occurs on SSH with ForwardX11 option

**Comment by chemzqm** [comment] 2020-11-16 11:52
Could be caused by request for prompt input, should be fixed now

**Closed by chemzqm** 2020-11-16 11:52 UTC
Labels: Can't reproduce
